# Generated by Django 4.2.3 on 2023-08-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0002_advertisements_image_advertisements_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisements',
            table='advertisements',
        ),
    ]
